{
  "load": "checkpoints_3rd_dec/dclm/inf_cos/ablations/low/const_1p/JOB-2885222__it-47684_wu-0.01_mxlr-0.0003_mnlr-3e-05_sch-cosine_constant_infinite_tr-dclm-train_resume",
  "save": "checkpoints_3rd_dec/dclm/inf_cos/ablations/low/const_1p",
}