{
  #  "pipe_parallel_size": 1,
   "model_parallel_size": 1,
   "make_vocab_size_divisible_by": 1,

   "num_layers": 24,
   "hidden_size": 1024,
   "num_attention_heads": 16,
   "seq_length": 2048,
   "max_position_embeddings": 2048,
   "norm": "rmsnorm",
   "pos_emb": "rotary",
   "rotary_pct": 1,
   "rms_norm_epsilon": 1.0e-6,
   "no_weight_tying": true,
   "scaled_upper_triang_masked_softmax_fusion": true,
   "bias_gelu_fusion": true,
   "rope_fusion": true,
   "layernorm_fusion": true,
   "num_workers": 1,
  #  "attention_config": [[["flash"], 24]],

  "output_layer_parallelism": "column",

  "use_bias_in_attn_linear": false,
  "mlp_type": "llama",
  "activation": "silu",
  "precision": "bfloat16",

   "fp32_allreduce": True,

   "optimizer": {
     "type": "Adam",
     "params": {
       "lr": 0.0006,
       "betas": [0.9, 0.999],
       "eps": 1.0e-8
     }
   },
   "zero_optimization": {
    "stage": 0,
    "allgather_partitions": true,
    "allgather_bucket_size": 500000000,
    "overlap_comm": true,
    "reduce_scatter": true,
    "reduce_bucket_size": 500000000,
    "contiguous_gradients": true
  },
   "train_micro_batch_size_per_gpu": 16,
   "data_impl": "mmap",
  #  "split": "949,50,1",
   "checkpoint_activations": true,
   "checkpoint_num_layers": 1,
   "partition_activations": true,
   "synchronize_each_layer": true,
   "gradient_clipping": 1.0,
   "weight_decay": 0.0,
   "hidden_dropout": 0.0,
   "attention_dropout": 0.0,
  #  "fp16": {
  #    "enabled": true,
  #    "loss_scale": 0,
  #    "loss_scale_window": 1000,
  #    "hysteresis": 2,
  #    "min_loss_scale": 1
  #  },
   "train_iters": 30000,
   "lr_decay_iters": 30000,
   "distributed_backend": "nccl",
   "lr_decay_style": "cosine",
   "warmup": 0.01,
   "checkpoint_factor": 6000,
   "eval_interval": 50,
   "eval_iters": 10,
   "log_interval": 10,
   "steps_per_print": 10,
   "keep_last_n_checkpoints": 4,
   "wall_clock_breakdown": true,
  #  "launcher": "slurm",
  #  "deepspeed_slurm": true,
   "comment": "neox",
  "constant_iters_percent" : 0.85,
}
