{
  "load": "/gpfs/alpine/csc499/scratch/kshitijkg/continued_training/gpt-neox/new_checkpoints/7_1B_scratch_Pile_infinite_inv",
  "save": "/gpfs/alpine/csc499/scratch/kshitijkg/continued_training/gpt-neox/new_checkpoints/7_1B_scratch_Pile_infinite_inv",
  "tensorboard-dir": "tensorboard_new/7_1B_scratch_Pile_infinite_inv",
  "log-dir": "/gpfs/alpine/csc499/scratch/kshitijkg/continued_training/gpt-neox/log_dir_new/7_1B_scratch_Pile_infinite_inv",
  "wandb_project": "7_1B_scratch_Pile_infinite_inv",
} 