{
  "load": "/gpfs/alpine/csc499/scratch/kshitijkg/neox_converted/deduped/pythia",
  "save": "/gpfs/alpine/csc499/scratch/kshitijkg/continued_training/gpt-neox/new_checkpoints/pythia_SP_taskwise_cosine",
  "tensorboard-dir": "tensorboard/pythia_SP_taskwise_cosine",
  "log-dir": "/gpfs/alpine/csc499/scratch/kshitijkg/continued_training/gpt-neox/log_dir/pythia_SP_taskwise_cosine",
  "wandb_project": "pythia_SP_taskwise_cosine",
}