{
  "load": "/gpfs/alpine/csc499/scratch/kshitijkg/continued_training/gpt-neox/new_checkpoints/scratch_Pile_SP_cosine",
  "save": "/gpfs/alpine/csc499/scratch/kshitijkg/continued_training/gpt-neox/new_checkpoints/scratch_Pile_SP_cosine",
  "tensorboard-dir": "tensorboard_new/scratch_Pile_SP_cosine",
  "log-dir": "/gpfs/alpine/csc499/scratch/kshitijkg/continued_training/gpt-neox/log_dir_new/scratch_Pile_SP_cosine",
  "wandb_project": "scratch_Pile_SP_cosine",
}