{
  # or for weighted datasets:
  "train-data-paths": [
    'data/slim_pajama/tokenized_train_100B-200B/ArXiv/ArXiv',
    'data/slim_pajama/tokenized_train_100B-200B/Book/Book',
    'data/slim_pajama/tokenized_train_100B-200B/C4/C4',
    'data/slim_pajama/tokenized_train_100B-200B/Wikipedia/Wikipedia',
    'data/slim_pajama/tokenized_train_100B-200B/Github/Github',
    'data/slim_pajama/tokenized_train_100B-200B/StackExchange/StackExchange',
    'data/slim_pajama/tokenized_train_100B-200B/CommonCrawl/CommonCrawl',

    'data/pile_replay_shards/replay_10B_2/splits',

    'data/sp_replay_shards/100B_1_shard1/ArXiv/ArXiv',
    'data/sp_replay_shards/100B_1_shard1/Book/Book',
    'data/sp_replay_shards/100B_1_shard1/C4/C4',
    'data/sp_replay_shards/100B_1_shard1/Wikipedia/Wikipedia',
    'data/sp_replay_shards/100B_1_shard1/Github/Github',
    'data/sp_replay_shards/100B_1_shard1/StackExchange/StackExchange',
    'data/sp_replay_shards/100B_1_shard1/CommonCrawl/CommonCrawl',
  ],
  "train-data-weights": [
    4.03666599074094,
    3.927523855378127,
    25.467175464208918,
    3.7984379710376293,
    4.990226864678155,
    3.1957646326079723,
    49.58420522134826,

    3.8125,

    # total: 1.1875,
    0.04337997179394097,
    0.04880477004015989,
    0.3205243831725252,
    0.0475528531698962,
    0.06249330493660256,
    0.03976979771580249,
    0.6249749191710727,
    ],
  "train-iters": 44229,
  "lr-decay-iters": 44229,
  "train-dataset-name": 'slim_pajama_100B_2_replay5',
}