{
  # or for weighted datasets:
  "train-data-paths": [
    'data/slim_pajama/train_300B/ArXiv/ArXiv',
    'data/slim_pajama/train_300B/Book/Book',
    'data/slim_pajama/train_300B/C4/C4',
    'data/slim_pajama/train_300B/Wikipedia/Wikipedia',
    'data/slim_pajama/train_300B/Github/Github',
    'data/slim_pajama/train_300B/StackExchange/StackExchange',
    'data/slim_pajama/train_300B/CommonCrawl/CommonCrawl',],
  "train-data-weights": [
    4.428184641, 
    4.203131326, 
    26.688499472, 
    3.997293125, 
    5.224141056, 
    3.371078725, 
    52.087671651
  ],
  "train-iters": 132366,
  "lr-decay-iters": 132366,
  "train-dataset-name": 'slim_pajama_300B',
}