{
  # or for weighted datasets:
  "train-data-paths": [
    'data/slim_pajama/tokenized_train_200B-300B/ArXiv/ArXiv',
    'data/slim_pajama/tokenized_train_200B-300B/Book/Book',
    'data/slim_pajama/tokenized_train_200B-300B/C4/C4',
    'data/slim_pajama/tokenized_train_200B-300B/Wikipedia/Wikipedia',
    'data/slim_pajama/tokenized_train_200B-300B/Github/Github',
    'data/slim_pajama/tokenized_train_200B-300B/StackExchange/StackExchange',
    'data/slim_pajama/tokenized_train_200B-300B/CommonCrawl/CommonCrawl',

    'data/pile_replay_shards/replay_10B_3/splits',

    'data/sp_replay_shards/100B_1_shard2/ArXiv/ArXiv',
    'data/sp_replay_shards/100B_1_shard2/Book/Book',
    'data/sp_replay_shards/100B_1_shard2/C4/C4',
    'data/sp_replay_shards/100B_1_shard2/Wikipedia/Wikipedia',
    'data/sp_replay_shards/100B_1_shard2/Github/Github',
    'data/sp_replay_shards/100B_1_shard2/StackExchange/StackExchange',
    'data/sp_replay_shards/100B_1_shard2/CommonCrawl/CommonCrawl',

    'data/sp_replay_shards/100B_2_shard1/ArXiv/ArXiv',
    'data/sp_replay_shards/100B_2_shard1/Book/Book',
    'data/sp_replay_shards/100B_2_shard1/C4/C4',
    'data/sp_replay_shards/100B_2_shard1/Wikipedia/Wikipedia',
    'data/sp_replay_shards/100B_2_shard1/Github/Github',
    'data/sp_replay_shards/100B_2_shard1/StackExchange/StackExchange',
    'data/sp_replay_shards/100B_2_shard1/CommonCrawl/CommonCrawl',
  ],
  "train-data-weights": [3.491756366873565,
    4.084283062119696,
    25.524317038754475,
    3.8109321899190314,
    4.89534056131328,
    3.254459546224121,
    49.93891123479581,
    
    3.088125,

    # total: 0.961875,
    0.03513777715309219,
    0.03953186373252951,
    0.2596247503697454,
    0.03851781106761592,
    0.05061957699864807,
    0.03221353614980002,
    0.506229684528569,

    #total: 0.95,
    0.0403666599074094,
    0.03927523855378127,
    0.25467175464208913,
    0.03798437971037629,
    0.049902268646781545,
    0.03195764632607972,
    0.4958420522134826,
    ],
  "train-iters": 44229,
  "lr-decay-iters": 44229,
  "train-dataset-name": 'slim_pajama_100B_3_replay5',
}