{
  "test-data-paths": ["data/pile/test/pile_test_text_document"],
  "test-data-weights": [
    1.
  ],
  "valid-data-paths": [
    ["data/pile/val/pile_val_text_document"],
    ["data/slim_pajama/val/all/sp_val"],
  ],
  "valid-data-weights": [
    [1.],
    [1.],
  ],
  "val-dataset-name": 'pile_slimp',
}
