
# Suggested data paths when using GPT-NeoX locally
{
  # "data-path": "data/enwik8/enwik8_text_document",

  # or for weighted datasets:
  # "train-data-paths": ["data/enwik8/enwik8_text_document", "data/enwik8/enwik8_text_document"],
  # "test-data-paths": ["data/enwik8/enwik8_text_document", "data/enwik8/enwik8_text_document"],
  # "valid-data-paths": ["data/enwik8/enwik8_text_document", "data/enwik8/enwik8_text_document"],
  
  # "train-data-weights": [1., 2.],
  # "test-data-weights": [2., 1.],
  # "valid-data-weights": [0.5, 0.4],

  "train-data-paths": ["data/german/train/train"] ,
  "test-data-paths": ["data/german/test/test"] ,
  "valid-data-paths": [["data/pile/val/pile_val_text_document"], ["data/german/val/val"]] ,
  
  # "train-data-paths": ["data/enwik8/enwik8_text_document", "data/enwik8/enwik8_text_document"],
  # "test-data-paths": ["data/enwik8/enwik8_text_document", "data/enwik8/enwik8_text_document"],
  # "valid-data-paths": ["data/enwik8/enwik8_text_document", "data/enwik8/enwik8_text_document"],
  
  "train-data-weights": [1.,],
  "test-data-weights": [1.,],
  "valid-data-weights": [[1.], [1.]],

  # If weight_by_num_documents is True, Builds dataset weights from a multinomial distribution over groups of data according to the number of documents in each group.
  # WARNING: setting this to True will override any user provided weights
  # "weight_by_num_documents": false,
  # "weighted_sampler_alpha": 0.3,

  # "vocab-file": "data/gpt2-vocab.json",

  "vocab_file": "data/20B_tokenizer.json",
  # "merge-file": "data/gpt2-merges.txt",
  "tokenizer_type": "HFTokenizer",

  "train-dataset-name": 'german_train',
  "val-dataset-name": 'pile_val',

  "save": "checkpoints",
  "load": "checkpoints/",
  "checkpoint_validation_with_forward_pass": False,

  "tensorboard-dir": "tensorboard",
  "log-dir": "logs",
  "use_wandb": False,
  "wandb_host": "https://api.wandb.ai",
  "wandb_project": "inf-lr",

  "launcher": "jsrun",
  "deepspeed_jsrun": true,

  # "train_on_new_dataset_from_old_checkpoint": true, # Set this to True only when a new Dataset comes, eg from Pile -> German
  "finetune": true,
  "num_workers": 4,
  
  "replay_config": {
    "enabled": true,
    # Have to specify idx filenames from original pretraining on tasks, as they contain the num iterations
    # and seen indices assuming we're using the same (non-replay) seed as during pretraining
    "replay_idx_paths_prefixes": [
      # "data/pile/train/pile_train_train_0_indexmap_146862725ns_2048sl_1234s",
      # "data/pile/train/pile_train_train_0_indexmap_1543680ns_2048sl_1234s",
      "data/pile/train/pile_train_train_0_indexmap_24120000ns_2048sl_1234s",
    ],
    "replay_data_weights":[
      1.00,
    ],
    "replay_idx_offsets": [
      1,
    ],
    # Fraction of samples coming from the replay buffer, between 0 and 1.
    "replay_fraction": 0.50,
    # Seed and reshuffle go hand in hand. They control whether you want to see the replay data in the same order
    # as you've seen it (done by setting reshuffle to false), and if you decide to reshuffle, what seed you should
    # use to reshuffle the seen data.
    "replay_seed": 1234,
    "replay_reshuffle_idx": false,
  },

}





