# Suggested data paths when using GPT-NeoX locally
{
  # "data_path": "data/enwik8/enwik8_text_document",
  #  "data_path": "data/german/train/train",
   "tokenizer-type": "HFTokenizer",

  "train-data-paths": ["data/german/train/train"] ,
  "test-data-paths": ["data/german/test/test"] ,
  
  # Select Pile for tracking accuracy on Pile while trainig is happening on German
  # TODO ask Ben, how to combine it efficiently. 

  # German val data
  # "valid-data-paths": ["data/german/val/val"] ,
  
  # Pile val data
  "valid-data-paths": ["data/pile/val/pile_val_text_document"] ,
  
  # "train-data-paths": ["data/enwik8/enwik8_text_document", "data/enwik8/enwik8_text_document"],
  # "test-data-paths": ["data/enwik8/enwik8_text_document", "data/enwik8/enwik8_text_document"],
  # "valid-data-paths": ["data/enwik8/enwik8_text_document", "data/enwik8/enwik8_text_document"],
  "train-data-weights": [1.,],
  "test-data-weights": [1.,],
  "valid-data-weights": [1.,],

  # If weight_by_num_documents is True, Builds dataset weights from a multinomial distribution over groups of data according to the number of documents in each group.
  # WARNING: setting this to True will override any user provided weights
  # "weight_by_num_documents": false,
  # "weighted_sampler_alpha": 0.3,

  "vocab_file": "data/20B_tokenizer.json",
  # "merge_file": "data/gpt2-merges.txt",

  "save": "./checkpoints",
  "load": "./checkpoints/JOB-4588193_49M_it-6000_wu-0_mxlr-0.000165_mnlr-0.000165_sch-constant_tr-pile-train_resume",

  # Choose the checkpoint where the model is finished training on Pile.
  # "load": "./checkpoints/JOB-4384461_49M_it-3000_wu-0.01_mxlr-0.0003_mnlr-3e-05_sch-cosine_tr-pile-train_resume",
  "checkpoint_validation_with_forward_pass": False,


  "train-dataset-name": 'german_train',
  "val-dataset-name": 'pile_val',

  "tensorboard_dir": "tensorboard",
  "log_dir": "logs",
  "use_wandb": False,
  "wandb_host": "https://api.wandb.ai",
  "wandb_project": "neox"
}