{
"optimizer": {
    "type": "Adam",
    "params": {
      "lr": 0.00165,
      "betas": [0.9, 0.95],
      "eps": 1.0e-8,
    }
  },
  "min_lr": 3.0e-6,
  "lr-decay-style": "cosine_cooldown_infinite",
  "warmup": 0,
  "constant_lr": 0.00165,
  "constant_iters_percent" : 0.85,
  "cooldown_iters_percent" : 0.6,
  "timescale" : 10,
  "override_lr_scheduler": True, # setting this to True, since we want to train on german for a constant lr
  "use_checkpoint_lr_scheduler": False # Again, we dont want to use the checkpoint's LR schedular. 
}
