{
  "load": "checkpoints_3rd_dec/german/inf_cos/ablations/low/const_1p75/JOB-2902534__it-47684_wu-0_mxlr-0.000175_mnlr-0.0_sch-constant_tr-german-train_resume",
  "save": "checkpoints_3rd_dec/german/inf_cos/ablations/low/const_1p75",
    "finetune": false,
}