{
  "test-data-paths": ["/gpfs/alpine/csc499/scratch/btherien/gpt-neox/data/pile/test/pile_test_text_document"],
  "test-data-weights": [
    1.
  ],
  "valid-data-paths": [
    ["/gpfs/alpine/csc499/scratch/btherien/gpt-neox/data/pile/val/pile_val_text_document"],
    ["/gpfs/alpine/csc499/scratch/btherien/gpt-neox/data/slim_pajama/val/all/sp_val"],
  ],
  "valid-data-weights": [
    [1.],
    [1.],
  ]
}
