{
  "test-data-paths": ["/gpfs/alpine/csc499/scratch/btherien/gpt-neox/data/red_pajama_400B/the_pile/test_tokenized_text_document"],
  "test-data-weights": [
    1.
  ],
  "valid-data-paths": [
    ["/gpfs/alpine/csc499/scratch/btherien/gpt-neox/data/red_pajama_400B/the_pile/val_tokenized_text_document"],
    [
      "/gpfs/alpine/csc499/scratch/btherien/gpt-neox/data/tokenized300B/val_splits/ArXiv/tokenized_text_document",
      "/gpfs/alpine/csc499/scratch/btherien/gpt-neox/data/tokenized300B/val_splits/Book/tokenized_text_document",
      "/gpfs/alpine/csc499/scratch/btherien/gpt-neox/data/tokenized300B/val_splits/C4/tokenized_text_document",
      "/gpfs/alpine/csc499/scratch/btherien/gpt-neox/data/tokenized300B/val_splits/Wikipedia/tokenized_text_document",
      "/gpfs/alpine/csc499/scratch/btherien/gpt-neox/data/tokenized300B/val_splits/Github/tokenized_text_document",
      "/gpfs/alpine/csc499/scratch/btherien/gpt-neox/data/tokenized300B/val_splits/StackExchange/tokenized_text_document",
      "/gpfs/alpine/csc499/scratch/btherien/gpt-neox/data/tokenized300B/val_splits/CommonCrawl/tokenized_text_document",
    ],
    ],
  "valid-data-weights": [
    [1.],
    [
    2.5,
    4.5,
    15.0,
    4.5,
    4.5,
    2.0,
    67.0
    ],
  ]

}
