{
"optimizer": {
    "type": "Adam",
    "params": {
      "lr": 3.0e-4,
      "betas": [0.9, 0.95],
      "eps": 1.0e-8,
    }
  },
  "min_lr": 3.0e-5,
  "lr-decay-style": "cosine-inf",
  "num_repeats": 3,
  "warmup": 0.01,
}