{
"optimizer": {
    "type": "Adam",
    "params": {
      "lr": 1.5e-4,
      "betas": [0.9, 0.95],
      "eps": 1.0e-8,
    }
  },
  "min_lr": 1.5e-5,
  "lr-decay-style": "cosine",
  "warmup": 0.,
  # "load": "/gpfs/alpine/csc499/scratch/btherien/gpt-neox/checkpoints/continued_test8/JOB-2959220_pythia-c-410M-iters-181793_warmup-0.01_max-lr-0.00015_min-lr-1.5e-05_finetune",
}