{
  "load": "checkpoints_3rd_dec/code/inf_cos/ablations/cooldown_proportion_0.6_replay/const_1p/JOB-3053416__it-47684_wu-0_mxlr-0.0001_mnlr-3e-05_sch-cosine_cooldown_infinite_tr-code-train_resume",
  "save": "checkpoints_3rd_dec/code/inf_cos/ablations/cooldown_proportion_0.6_replay/const_1p",
  "finetune": false,
}