{
  "pipe_parallel_size": 16,
  "model_parallel_size": 8,
  "num_layers": 24,
  "hidden_size": 1024,
  "num_attention_heads": 16,
  "seq_length": 2048,
  "max_position_embeddings": 2048,
  "pos_emb": "rotary",
  "rotary_pct": 0.25,
  # "mlp_type": "llama",
  "activation": "silu",
  "no_weight_tying": true,
  "gpt_j_residual": true,
  "output_layer_parallelism": "column",
  # "attention_config": [[["flash"], 24]],
   "scaled_upper_triang_masked_softmax_fusion": true,
   "bias_gelu_fusion": true,
   "rope_fusion": true,
   "layernorm_fusion": true,

   "zero_optimization": {
    "stage": 1,
    "allgather_partitions": true,
    "allgather_bucket_size": 200000000,
    "overlap_comm": true,
    "reduce_scatter": true,
    "reduce_bucket_size": 200000000,
    "contiguous_gradients": true,
    "cpu_offload": false
  },
   "train_micro_batch_size_per_gpu": 4,
   "gradient_accumulation_steps": 1,
   "data_impl": "mmap",
   "checkpoint_activations": true,
   "checkpoint_num_layers": 1,
   "partition_activations": true,
   "synchronize_each_layer": true,
   "gradient_clipping": 1.0,
   "weight_decay": 0.1,
   "hidden_dropout": 0.0,
   "attention_dropout": 0.0,
  "precision": "bfloat16",
  "fp32_allreduce": true,
  "bf16": {
    "enabled": true
  },
  "data_types": {
    "grad_accum_dtype": "fp32"
  },
   "train_iters": 1000,
   "lr_decay_iters": 1000,
   "distributed_backend": "nccl",
   "checkpoint_factor": 500,
   "eval_interval": 50,
   "eval_iters": 10,
   "log_interval": 10,
   "steps_per_print": 10,
   "keep_last_n_checkpoints": 4,
   "wall_clock_breakdown": true,
   "launcher": "slurm",
   "deepspeed_slurm": true,
   "num_workers": 1,
     
}