{
  "load": "checkpoints_3rd_dec/code/inf_cos/ablations/cooldown_proportion_0.3/without_replay/const_2p/JOB-3053349__it-47684_wu-0_mxlr-0.0002_mnlr-3e-05_sch-cosine_cooldown_infinite_tr-code-train_resume",
  "save": "checkpoints_3rd_dec/code/inf_cos/ablations/cooldown_proportion_0.3/without_replay/const_2p",
  "finetune": false,
}