{
  # or for weighted datasets:
  "train-data-paths": [
    '/gpfs/alpine/csc499/scratch/kshitijkg/continued_training/gpt-neox/data/slim_pajama_300B/C4/C4',
    ],
  "train-data-weights": [
    1.0,
  ],

  # 79872895846
}