{
  # or for weighted datasets:
  "train-data-paths": [
    '/gpfs/alpine/csc499/scratch/kshitijkg/continued_training/gpt-neox/data/slim_pajama_300B/CommonCrawl/CommonCrawl',],
  "train-data-weights": [
    1.0,
  ],

  # 155887114486
  "train-iters": 68946,
}