{
  # or for weighted datasets:
  "train-data-paths": [
    '/gpfs/alpine/csc499/scratch/kshitijkg/continued_training/gpt-neox/data/slim_pajama_300B/StackExchange/StackExchange',
    ],
  "train-data-weights": [
    1.0,
  ],
  # 10088908154
}