# Suggested data paths when using GPT-NeoX locally
{
  # "data-path": "data/enwik8/enwik8_text_document",

  # or for weighted datasets:
  "train-data-paths": [
    "/gpfs/alpine/csc499/proj-shared/red_pajama_data/arxiv/arxiv_tokenized_text_document",
    "/gpfs/alpine/csc499/proj-shared/red_pajama_data/book/book_tokenized_text_document",
    "/gpfs/alpine/csc499/proj-shared/red_pajama_data/c4/processed_en/c4_tokenized_text_document",
    "/gpfs/alpine/csc499/proj-shared/red_pajama_data/wikipedia/wiki_full_tokenized_text_document",
    "/gpfs/alpine/csc499/proj-shared/red_pajama_data/github/tokenized_text_document",
    "/gpfs/alpine/csc499/proj-shared/red_pajama_data/cc_classifier_filtered/2019-30/tokenized_text_document",
    "/gpfs/alpine/csc499/proj-shared/red_pajama_data/cc_classifier_filtered/2020-05/tokenized_text_document",
    "/gpfs/alpine/csc499/proj-shared/red_pajama_data/cc_classifier_filtered/2021-04/tokenized_text_document",
    "/gpfs/alpine/csc499/proj-shared/red_pajama_data/cc_classifier_filtered/2022-05/tokenized_text_document",
    "/gpfs/alpine/csc499/proj-shared/red_pajama_data/cc_classifier_filtered/2023-06/tokenized_text_document",
  ],
  "test-data-paths": ["/gpfs/alpine/csc499/proj-shared/red_pajama_data/the_pile/test_tokenized_text_document"],
  "valid-data-paths": ["/gpfs/alpine/csc499/proj-shared/red_pajama_data/the_pile/val_tokenized_text_document"],
  "train-data-weights": [
    2.5,
    4.5,
    15.0,
    4.5,
    4.5,
    13.4,
    13.4,
    13.4,
    13.4,
    13.4
  ],
  "test-data-weights": [
    1.
  ],
  "valid-data-weights": [
    1.
  ],

  "finetune": true,
  "tokenizer-type": "HFTokenizer",
  "vocab_file": "data/20B_tokenizer.json",

  "save": "checkpoints",
  "load": "/gpfs/alpine/csc499/scratch/btherien/neox_converted/mp1_pp1/pythia/410m",

  "checkpoint_validation_with_forward_pass": False,

  "tensorboard-dir": "tensorboard",
  "log-dir": "logs",
  "use_wandb": True,
  "wandb_host": "https://api.wandb.ai",
  "wandb_project": "neox"
}
