{
"optimizer": {
    "type": "Adam",
    "params": {
      "lr": 3.0e-3,
      "betas": [0.9, 0.95],
      "eps": 1.0e-8,
    }
  },
  "min_lr": 3.0e-6,
  "lr-decay-style": "cosine_cooldown_infinite",
  "warmup": 0.01,
  "constant_lr": 1.65e-3,
  "constant_iters_percent" : 0.85,
  "cooldown_iters_percent" : 0.6,
  "timescale" : 10,
}