{
  "load": "checkpoints_3rd_dec/code/inf_cos/ablations/high/const_3/JOB-3017096__it-47684_wu-0_mxlr-0.0003_mnlr-3e-05_sch-cosine_cooldown_infinite_tr-code-train_resume",
  "save": "checkpoints_3rd_dec/code/inf_cos/ablations/high/const_3",
  "finetune": false,
}